<a href="https://colab.research.google.com/github/amudha1/Tensorflow/blob/master/First_TensorFlow_NeuralNetwork_Justbasics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Neuron that produces a simple linear fit to a 2D data

In [0]:
Steps:
    1)Build a graph
    2)Initiate the session
    3)Feed the data in and get the output
    

-See the graph and constuct it
-Add the cost function and train 
-Feed the data and get the output

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
np.random.seed(101)
tf.set_random_seed(101)

In [10]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[99.43179012, 52.06653967, 57.87895355, 73.48190583, 54.19617722],
       [91.31535577, 80.7920151 , 40.29978307, 35.72243428, 95.28767147],
       [34.36315779, 86.50998163, 83.02777122, 53.81614492, 92.24693726],
       [ 9.71464798, 10.28474932, 70.15072957, 89.04798691, 15.95603009],
       [27.55725449, 67.24915297, 16.4303124 , 70.13711366, 48.76352222]])

In [25]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[36.22733551],
       [35.65020139],
       [19.52516005],
       [98.73127505],
       [ 2.33054924]])

In [0]:
a = tf.placeholder(tf.float32)

In [0]:
b = tf.placeholder(tf.float32)

In [0]:
add_op = a + b

In [0]:
mul_op = a * b

In [19]:
with tf.Session() as sess:
    result = sess.run(add_op,feed_dict={a:10,b:20})
    print(result)

30.0


In [26]:
with tf.Session() as sess:
    print(sess.run(add_op,feed_dict={a:rand_a,b:rand_b}))

[[135.65913   88.29388   94.10629  109.70924   90.423515]
 [126.96555  116.442215  75.94998   71.372635 130.93787 ]
 [ 53.88832  106.03514  102.55293   73.3413   111.7721  ]
 [108.44592  109.01603  168.882    187.77927  114.68731 ]
 [ 29.887804  69.579704  18.760862  72.46767   51.09407 ]]


In [27]:
with tf.Session() as sess:
    print(sess.run(mul_op,feed_dict={a:rand_a,b:rand_b}))

[[3602.1492   1886.232    2096.8003   2662.0537   1963.3832  ]
 [3255.4106   2880.2515   1436.6953   1273.512    3397.0247  ]
 [ 670.94617  1689.1212   1621.1305   1050.7688   1801.1362  ]
 [ 959.13965  1015.4264   6926.071    8791.821    1575.3593  ]
 [  64.22354   156.72746    38.291653  163.45801   113.64579 ]]


Next -  **Regression Example:**