<a href="https://colab.research.google.com/github/amudha1/Tensorflow/blob/master/Play_with_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
my_first_matt = tf.fill((4,4),5)

In [0]:
random_disribution_matrix=tf.random_normal((4,4),3)

In [7]:
with tf.Session() as session:
    print(session.run(random_disribution_matrix))
    

[[3.4955559 3.2034793 4.156783  3.4166532]
 [3.985452  3.043192  4.731942  1.7610933]
 [1.3476316 2.6505818 2.5119886 4.630723 ]
 [3.5342624 2.9150767 2.9143424 2.8167977]]


In [0]:
a = tf.constant([[10,10],[20,20]])

In [0]:
b = tf.constant([[15,20],[18,16]])

In [0]:
c = tf.matmul(a,b)

In [14]:
with tf.Session() as sess:
    print(sess.run(c))

[[330 360]
 [660 720]]
