<a href="https://colab.research.google.com/github/amudha1/Tensorflow/blob/master/Variables_and_place_holders_in_a_graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

There are 2 main types of tensor objects in a graph
1)Variables
2)Place holders

Variable properties:
1)Variables can hold the values weights and biases thought the session
2)Variables need to be initialized

In [0]:
PlaceHolders: These are initially empty and are used to feed in the training examples.
However they do need a expected data type and optional shape argument

In [0]:
import tensorflow as tf

In [0]:
my_tensor = tf.random_uniform((4,4),0,1)
    

In [11]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [23]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(my_tensor))

[[0.5970912  0.9377837  0.36999583 0.63332474]
 [0.42932308 0.7401483  0.6349038  0.8361764 ]
 [0.91160905 0.7964659  0.33479953 0.79890966]
 [0.47559583 0.23685098 0.35872912 0.83728755]]


In [0]:
sess  = tf.InteractiveSession()

In [0]:
my_var = tf.Variable(my_tensor)

In [0]:
sess.run(tf.global_variables_initializer())

In [32]:
sess.run(my_var)

array([[0.27061868, 0.74285984, 0.69727993, 0.01922464],
       [0.5809337 , 0.49860907, 0.10335433, 0.7538544 ],
       [0.06685483, 0.15883219, 0.53972197, 0.7523658 ],
       [0.12828267, 0.9851067 , 0.6240957 , 0.97321725]], dtype=float32)

In [0]:
ph = tf.placeholder(tf.float32,shape=(None,5))